name: front-end-publish-docker-image

# Action triggered when pushing 'front-end' directory in 'main' branch
on:
  push:
    branches: 
      - main
    paths: 
      - front-end/**

# Run jobs on front-end directory
defaults:
  run:
    working-directory: front-end

# Environment variables
env:
  DOCKER_IMAGE_NAME: ullsoftware/front-end

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout of the repository
      - uses: actions/checkout@v3
        name: Check out code
      # Build and publish Docker image in DockerHub
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.DOCKER_IMAGE_NAME }}
          tags: latest
          registry: docker.io
          directory: front-end
          dockerfile: front-end/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          buildArgs: GITHUB_TOKEN=${{ secrets.KAIZTEN_DEVELOPMENT_PASSWORD }}