name: back-end-publish-docker-image

# Action triggered when pushing 'back-end' directory in 'main' branch
on:
  push:
    branches:
      - main
    paths:
      - back-end/**

# Run jobs on 'back-end' directory
defaults:
  run:
    working-directory: back-end

# Environment variables
env:
  DOCKER_IMAGE_NAME: ullsoftware/back-end    

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      # Checkout of the repository
      - name: Checkout
        uses: actions/checkout@v3
      # Setting JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      # Build artifact with Maven
      - name: Build with Maven
        run: mvn -B -Pull-tfg clean package --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.ULLSOFTWARE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.ULLSOFTWARE_PASSWORD }}
      # Build and publish Docker image in DockerHub
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.DOCKER_IMAGE_NAME }}
          tags: latest
          registry: docker.io
          directory: back-end
          dockerfile: back-end/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}